name: changedetection
description: A generated Helm Chart for changedetection from Skippbox Kompose
version: 0.0.0
apiVersion: v2
keywords:
  - changedetection
sources:
  - https://github.com/dgtlmoon/changedetection.io
home: https://github.com/dgtlmoon/changedetection.io