apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: changedetection
  name: changedetection
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: changedetection
                port:
                  number: {{ .Values.changedetectionNetwork.webPort }}
            path: /
            pathType: Prefix
status:
  loadBalancer: {}
