apiVersion: v1
kind: Service
metadata:
  labels:
    app: playwright-chrome
  name: playwright-chrome
spec:
  ports:
    - name: "ws"
      port: 3000
      targetPort: 30000
  selector:
    app: playwright-chrome
  type: ClusterIP
status:
  loadBalancer: {}
